version: '3.4'

services:
  worker:
    image: debian:latest
    restart: always
    volumes:
      - "./demo/worker/writefile.sh:/app/writefile.sh"
      - "./demo/volume/etc/nginx/proxy.conf:/etc/nginx/conf.d/default.conf"
      - "share:/sharedata"
    entrypoint: "/bin/bash -c 'trap exit TERM; while :; do /app/writefile.sh > /etc/nginx/conf.d/default.conf ;/app/writefile.sh > /sharedata/default.conf ; sleep 5s & wait $${!}; done;'"


  web1:
    container_name: web1
    restart: always
    image: nginx
    ports:
      - 8080:80
    volumes:
      - "./demo/volume/etc/nginx/proxy.conf:/etc/nginx/conf.d/default.conf"
      - "share:/sharedata"

  filewatcher:
    image: filewatcher
    build:
      context: .
      dockerfile: src/Dockerfile
    restart: always
    environment:
     - FileWatcher_path=/etc
     - FileWatcher_time=15
     - FileWatcher_recurse=true
     - FileWatcher_command=sh
     - FileWatcher_arguments=-c,""

    volumes:
      - "./demo/volume/etc/nginx/proxy.conf:/etc/nginx/conf.d/default.conf"
      - "share:/sharedata"


volumes:
  share: 