version: "3.4"

services:
  web1:
    restart: always
    image: nginx
    ports:
      - 8080:80
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"

  web2:
    restart: always
    build:
      context: ./install
    environment:
      - filewatcher_time=15
    ports:
      - 8080:80
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
