version: "3.7"

services:
  worker:
    image: debian:latest
    restart: always
    volumes:
      - "./worker/writefile.sh:/app/writefile.sh"
      - "./volume/etc/nginx/proxy.conf:/etc/nginx/conf.d/default.conf"
      - "share:/sharedata"
    entrypoint: "/bin/bash -c 'trap exit TERM; while :; do /app/writefile.sh > /etc/nginx/conf.d/default.conf ;/app/writefile.sh > /sharedata/default.conf ; sleep 5s & wait $${!}; done;'"

  web1:
    container_name: web1
    restart: always
    image: nginx
    ports:
      - 8080:80
    volumes:
      - "./volume/etc/nginx/proxy.conf:/etc/nginx/conf.d/default.conf"
      - "share:/sharedata"

  # web2:
  #   container_name: web2
  #   restart: always
  #   build:  ../src
  #   dockerfile: Dockerfile-nginx
  #   ports:
  #     - 8081:80
      
  #   volumes:
  #     - "./volume/etc/nginx/proxy.conf:/etc/nginx/conf.d/default.conf"
  #     - "./volume/etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
  #     - "share:/sharedata"

  app:
    container_name: app
    restart: always
    build:  ../src
    command: "/app/FileWatcher --path /etc/nginx/conf.d -t 10"
    volumes:
      - "./volume/etc/nginx/proxy.conf:/etc/nginx/conf.d/default.conf"
      - "share:/sharedata"

  notify:
    container_name: notify
    restart: always
    build:  ./notify
    entrypoint: "inotifywait --exclude .swp -e create -e modify -e delete -e move /sharedata"
    volumes:
      - "./volume/etc/nginx/proxy.conf:/etc/nginx/conf.d/default.conf"
      - "share:/sharedata"

volumes:
  share: 